### ISSUE TITLE
Add-on crashes whenever credentials required

### ISSUE THREAD

**Issue by markedup** [yamboo-efi/plugin.video.flix2kodi#12]
## Hardware & Software
**System:** Raspberry Pi 3+
**Platform:** LibreELEC v8.2.5 (based on Kodi v17 'Krypton')
**Add-on:** Flix2Kodi v0.6.9

## Replication steps
1. Create latest stable LibreELEC MicroSD card image using LibreELEC tool for Windows.
2. Insert MicroSD card into Pi 3 and boot; run through standard LibreELEC/Kodi setup.
3. Install **Flix2Kodi add-on** via USB stick.
4. Install **InputStream Adaptive add-on** via default Kodi 18 repos.
5. Install **RTMP Input add-on** via default Kodi 18 repos.
6. Once all installs completed, reboot Kodi for good measure.
7. Navigate to "Add-ons" in Kodi main menu and start Flix2Kodi; enter user credentials, select "Chromelauncher" as browser, and continue.

## Result
Go to any category and attempt a search or to load past activity; Flix2Kodi add-on reports a crash upon transmitting user credentials to Netflix. Also setting "Chromelauncher" as the browser in Flix2Kodi's initial settings [_see step 7_] seems to have no effect on the interface; I'm still browsing around Netflix's data using Kodi's bare folders/lists views.

## Expected behaviour
1. Browse Netflix using a visual interface with film/series posters, etc.
2. Able to free-text search, or view past account activity.
3. Select and play a series episode or film.

Can anyone help with what step(s) I might have missed or gotten wrong above?

**Comment by yamboo-efi** [comment]
Hi,

Launch Kodi and reproduce the issue, next please attach the log, you can get it from ~/.kodi/temp/kodi.log. Before attach, obfuscate you credentials in the log if they are present.

Thanks.
